import React from "react";
import type { Metadata } from "next";

//** Components */
import HeaderComponent from "@commonComponents/Header";
import FooterComponent from "@commonComponents/Footer";
import MenuComponent from "@commonComponents/Menu";

//** Styles */
import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <HeaderComponent />
                <MenuComponent />
                <main className="min-h-screen">{children}</main>
                <FooterComponent />
            </body>
        </html>
    );
}
