import React from "react";
import type { Metadata } from "next";

//** Components */
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
// import Menu from "@/components/Menu";

//** Styles */
import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                {/* <Menu /> */}
                <main className="min-h-screen">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
