import React from "react";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main className="min-h-screen">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
